apiVersion: v1
kind: Service
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  selector:
    app: myapp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - secretName: myapp-ssl
      hosts:
        - myapp.mydomain.com
  rules:
    - host: myapp.mydomain.com
      http:
        paths:
          - path: /
            backend:
              serviceName: myapp
              servicePort: http

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      volumes:
      - name: auth-git
        secret:
          secretName: auth-git
      imagePullSecrets:
        - name: internal-pull-secret
      containers:
      - name: meteor
        image: ulexus/testapp:v7
        livenessProbe:
          httpGet:
            port: 3000
          initialDelaySeconds: 400
        readinessProbe:
          httpGet:
            port: 3000
        ports:
        - name: http
          containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: ROOT_URL
          value: https://myapp.mydomain.com
        - name: MONGO_URL
          value: mongodb://10.20.30.40:27017,10.20.30.41:27017,10.20.30.42:27017/myapp?replicaSet=prod
        - name: MONGO_OPLOG_URL
          value: mongodb://10.20.30.40:27017,10.20.30.41:27017,10.20.30.42:27017/myapp?replicaSet=prod
          value: mongodb://10.20.30.40:27017,10.20.30.41:27017,10.20.30.42:27017/local?replicaSet=prod
        volumeMounts:
        - name: "auth-git"
          readOnly: true
          mountPath: /etc/meteor

